### PR TITLE
added languages. updated versions

### PR DESCRIPTION
**Pull request by restlessronin**
bumped existing grammars to latest versions

added packages for r, markdown, objective c, swift, scala, kotlin

### CODE REVIEW

**Comment by restlessronin** [comment]
Hi @Gregoor , any update on this PR?

**Comment by Gregoor** [comment]
Oh thanks for the ping, this slipped through the cracks

**Comment by Gregoor** [comment]
@restlessronin I'm sorry to report that `tree-sitter-markdown` did not make the cut as there was an error during building:
https://github.com/Gregoor/tree-sitter-wasms/actions/runs/8114705218/job/22180952657
It did built for me locally though, but I atm don't have the time to figure out why it didn't in GHA. Feel free to ping  me if you find sth out, it'd be great to have support for it.

**Comment by restlessronin** [comment]
@Gregoor noted. On first glance, I couldn't understand what was happening either. I'm in the middle of other stuff, but will circle around to this, the next time I'm working with it.

**Pull request merged**
